name: Daily Domain Monitor

on:
  schedule:
    - cron: '0 8 * * *'   # 每天北京时间 16:00
  workflow_dispatch:      # 手动触发

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Download and Run
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COOKIE: ${{ secrets.COOKIE }}
          SENDKEY: ${{ secrets.SENDKEY }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          # 1. 下载最新 Release 中的二进制文件
          # 使用 gh 工具下载，自动处理权限认证
          gh release download --repo ${{ github.repository }} --pattern "domain-monitor" --output domain-monitor

          # 2. 赋予执行权限
          chmod +x domain-monitor

          # 3. 运行程序
          ./domain-monitor